{{- $fullName := include "accent.fullname" . -}}
{{- if .Values.image.imageCredentials }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-registry-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "accent.imagePullSecret" . }}
{{- end }}