apiVersion: v1
kind: Secret
metadata:
  name: {{ include "accent.fullname" . }}-env
  labels:
    {{- include "accent.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.ENV_VARS }}
  {{ $key }}: {{ $val | toString| b64enc | quote }}
  {{- end }}